### ISSUE TITLE
install.sh does not work as expected

### ISSUE THREAD

**Issue by vslepakov** [Azure-Samples/iot-edge-for-iiot#1]
Hey follks, 

tried to run `install.sh ` a couple of times. Resources get provisioned but IoT Edge instances are not initialized (no connection string, cert settings etc.  in `config.yaml`) the iotedge.service is masked and I have the feeling that the NSG configuration might not be correct (L5 just allows AMQP port 5671 for outbound, how to download container images then?).
Is it right now as designed and one should follow this [manual guide](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11&tabs=azure-portal)?

Thanks!

**Comment by bamajeed** [comment]
I have a similar issue to Vitaliy, no connection strings. Also the script fails if the subscription name has a space

**Comment by vslepakov** [comment]
thanks @ebertrams for fixing, works for me now!
