### ISSUE TITLE
install.sh fails if the subscription name has a space

### ISSUE THREAD

**Issue by toddysm** [Azure-Samples/iot-edge-for-iiot#14]
The following line (131) in the install.sh break the installation if the subscription name has space:

```
subscription=$(az account show --query 'name' -o tsv)
```

It is better to use the subscription ID instead everywhere in the scripts. Lines above use the specified parameter for subscription ID.

**Comment by ebertrams** [comment]
Fixed with PR https://github.com/Azure-Samples/iot-edge-for-iiot/pull/27
