### ISSUE TITLE
Azure DevOps pipeline failed with default agent version

### ISSUE THREAD

**Issue by vjrantal** [Azure-Samples/iot-edge-for-iiot#29]
In the second part of the instructions a pipeline in Azure DevOps is created.

The first run of the pipeline failed with this error:

<img width="1157" alt="Screenshot 2021-03-31 at 9 41 25" src="https://user-images.githubusercontent.com/207474/113101968-05d16480-9206-11eb-8592-41a2482590b0.png">

It looks like the same issue that is reported [here](https://github.com/microsoft/azure-pipelines-tasks/issues/13641).

**Comment by ebertrams** [comment]
Thanks a raising this issue and providing the fix at the same time @vjrantal :) Onder, used your fix to fix the dev ops pipeline and merged that with his pr. So this issue can now be closed.
