### ISSUE TITLE
Iot edge devices runtime status showing error

### ISSUE THREAD

**Issue by sg33452** [Azure-Samples/iot-edge-for-iiot#40]
After deploying the simulation script successfully, I have found the IoT Edge devices/modules not going to running status.
Could you please clarify whether how to solve this or is there anything I have missed any steps?

**Comment by ebertrams** [comment]
Hi @sg33452, the root cert has expired and I m working on updating them. Because of that the installation of IoT Edge runtime fails. Stay tuned for an update!

**Comment by ebertrams** [comment]
Certs are now fixed. So you can redeploy and issue should go away.
