### ISSUE TITLE
Install script fails to parse json topLayerBaseDeploymentItProxy.json

### ISSUE THREAD

**Issue by judyer28** [Azure-Samples/iot-edge-for-iiot#9]
Script seemed to run successfully all the way to the pushing of base deployment and then this error message:  

===========================================================
==   Pushing base deployment to all IoT Edge devices     ==
===========================================================

sed: -e expression #1, char 103: unknown option to `s'
L5-edge...
Failed to parse json from file: '/home/justin/iot-edge-for-iiot/scripts/./edgeDeployments/topLayerBaseDeploymentItProxy.json' for argument 'content' with exception:
    Expecting value: line 1 column 1 (char 0)
L4-edge...
L3-edge...
done

**Comment by ebertrams** [comment]
Hi @judyer28 , i was not able to repro. Some changes were made yesterday to support some more charaters when copy/pasting ACR passwords. Did you see this bug after yesterday's change? If yes, is it possible that you share with me the ACR credentials that you use. It is possible that some special characters are still not parsed properly. You can send them to me privately by email to ebertra at microsoft.com. Thanks!

**Comment by judyer28** [comment]
Hello @ebertrams, thank you for your reply.  I just cloned the latest version and ran the scripts again and this time it worked.
